name: Generate Snake Animation

on:
  schedule:
    - cron: "0 4 * * *"   # diario a las 04:00 UTC (~00:00 hora Bolivia, UTC-4)
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: alekai21
          outputs: |
            assets/contributions-snake-dark.svg?color_snake=%23FFFFFF&color_dots=%230D1117,%23404040,%23808080,%23C0C0C0,%23FFFFFF&color_animals=%23FFFFFF
            assets/contributions-snake-light.svg?color_snake=%23000000&color_dots=%23FFFFFF,%23D3D3D3,%23808080,%23404040,%23000000&color_animals=%23000000

      - name: Push generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake [skip ci]"
          file_pattern: assets/contributions-snake-*.svg
